import type { createActivation } from "./activation";
import type { createDocsNightly } from "./docs-nightly";
import type { createProbes } from "./probes";
import type { createReconcile } from "./reconcile";
import type { createStageChildren } from "./stages/children";
import type { createDocsStage } from "./stages/docs";
import type { createMemoryStage } from "./stages/memory";
import type { createNightStages } from "./stages/night";
import type { createOnboardingStage } from "./stages/onboarding";
import type { createProjectLifeStage } from "./stages/project-life";
import type { createQaStages } from "./stages/qa";
import type { createWriterHost } from "./writer-host";
import type { createWriterRun } from "./writer-run";

type ActivationApi = ReturnType<typeof createActivation>;
type DocsNightlyApi = ReturnType<typeof createDocsNightly>;
type ProbesApi = ReturnType<typeof createProbes>;
type ReconcileApi = ReturnType<typeof createReconcile>;
type StageChildrenApi = ReturnType<typeof createStageChildren>;
type DocsStageApi = ReturnType<typeof createDocsStage>;
type MemoryStageApi = ReturnType<typeof createMemoryStage>;
type NightStagesApi = ReturnType<typeof createNightStages>;
type OnboardingStageApi = ReturnType<typeof createOnboardingStage>;
type ProjectLifeStageApi = ReturnType<typeof createProjectLifeStage>;
type QaStagesApi = ReturnType<typeof createQaStages>;
type WriterHostApi = ReturnType<typeof createWriterHost>;
type WriterRunApi = ReturnType<typeof createWriterRun>;

/** Every function one server module offers another; filled once all modules exist, read at call time. */
export interface Services {
  DOCS_NIGHT_ATTEMPTS: DocsNightlyApi["DOCS_NIGHT_ATTEMPTS"];
  DOCS_OPEN_KEY: DocsNightlyApi["DOCS_OPEN_KEY"];
  DOCS_TOOLING: DocsNightlyApi["DOCS_TOOLING"];
  DOCS_UNITS_OPEN_KEY: DocsNightlyApi["DOCS_UNITS_OPEN_KEY"];
  DOCS_UNIT_CONCURRENCY: DocsNightlyApi["DOCS_UNIT_CONCURRENCY"];
  WORKSPACE_DOCS_MIN_FILES: DocsNightlyApi["WORKSPACE_DOCS_MIN_FILES"];
  activate: ActivationApi["activate"];
  activeWriterTasks: WriterRunApi["activeWriterTasks"];
  applyOnboardingPreview: OnboardingStageApi["applyOnboardingPreview"];
  assertComposerEnvironment: ActivationApi["assertComposerEnvironment"];
  dispatchCli: WriterRunApi["dispatchCli"];
  dispatchWriter: WriterRunApi["dispatchWriter"];
  docsPassesRunning: DocsNightlyApi["docsPassesRunning"];
  docsSpawnGate: DocsNightlyApi["docsSpawnGate"];
  docsUnitRecordKey: DocsNightlyApi["docsUnitRecordKey"];
  docsUnitsFinishing: DocsNightlyApi["docsUnitsFinishing"];
  docsUnitsIndexChain: DocsNightlyApi["docsUnitsIndexChain"];
  dropDocsUnitRecord: DocsNightlyApi["dropDocsUnitRecord"];
  enqueueResumedWriter: ReconcileApi["enqueueResumedWriter"];
  finishDocsUnit: DocsNightlyApi["finishDocsUnit"];
  finishWriterAttempt: WriterRunApi["finishWriterAttempt"];
  ingestOpenCodeTelemetry: QaStagesApi["ingestOpenCodeTelemetry"];
  listedAgentProfiles: WriterHostApi["listedAgentProfiles"];
  maintainMemoryAfterAcceptance: MemoryStageApi["maintainMemoryAfterAcceptance"];
  maintainProjectLifeAfterAcceptance: ProjectLifeStageApi["maintainProjectLifeAfterAcceptance"];
  maybeFinishResumedAttempt: ReconcileApi["maybeFinishResumedAttempt"];
  persistWriterAcceptance: WriterRunApi["persistWriterAcceptance"];
  pluginStopped: DocsNightlyApi["pluginStopped"];
  projectLifeTaskSummary: StageChildrenApi["projectLifeTaskSummary"];
  readWriterWorkspaceFile: WriterRunApi["readWriterWorkspaceFile"];
  reconcileAttemptThread: ReconcileApi["reconcileAttemptThread"];
  reconcileDocsChild: StageChildrenApi["reconcileDocsChild"];
  reconcileProjectLifeChild: StageChildrenApi["reconcileProjectLifeChild"];
  reconcileStageChild: StageChildrenApi["reconcileStageChild"];
  recoverLostHolderThread: ReconcileApi["recoverLostHolderThread"];
  resolveProjectWriterHost: WriterHostApi["resolveProjectWriterHost"];
  resumeOrphans: ReconcileApi["resumeOrphans"];
  runBrowserQa: QaStagesApi["runBrowserQa"];
  runDocsCatchUps: DocsNightlyApi["runDocsCatchUps"];
  runDocsMaintenance: DocsStageApi["runDocsMaintenance"];
  runDocsUnit: DocsNightlyApi["runDocsUnit"];
  runGateTriage: NightStagesApi["runGateTriage"];
  runMemoryContext: MemoryStageApi["runMemoryContext"];
  runMemoryMaintenance: MemoryStageApi["runMemoryMaintenance"];
  runNightFix: NightStagesApi["runNightFix"];
  runNightReview: NightStagesApi["runNightReview"];
  runNightlyDocs: DocsNightlyApi["runNightlyDocs"];
  runOnboardingPreview: OnboardingStageApi["runOnboardingPreview"];
  runProjectLifeMaintenance: ProjectLifeStageApi["runProjectLifeMaintenance"];
  runScheduledDocsMaintenance: DocsNightlyApi["runScheduledDocsMaintenance"];
  runVerification: WriterRunApi["runVerification"];
  runWorkspaceStatus: NightStagesApi["runWorkspaceStatus"];
  runWriterPool: WriterRunApi["runWriterPool"];
  saveDocsUnitRecord: DocsNightlyApi["saveDocsUnitRecord"];
  selectionCatalogHost: WriterHostApi["selectionCatalogHost"];
  spawnDocsThread: DocsNightlyApi["spawnDocsThread"];
  spawnWriterAttempt: WriterRunApi["spawnWriterAttempt"];
  startAmbiguousProbe: ProbesApi["startAmbiguousProbe"];
  startCancelProbe: ProbesApi["startCancelProbe"];
  startProviderErrorProbe: ProbesApi["startProviderErrorProbe"];
  startWriterTask: WriterRunApi["startWriterTask"];
  threadReconcilePort: ReconcileApi["threadReconcilePort"];
  unitWritable: DocsNightlyApi["unitWritable"];
  updateDocsUnitsIndex: DocsNightlyApi["updateDocsUnitsIndex"];
  validateWriterResult: WriterRunApi["validateWriterResult"];
  waitWriter: WriterRunApi["waitWriter"];
  workspaceDirt: WriterRunApi["workspaceDirt"];
}
