import type { CouncilApi } from "./council";
import type { ErrandsApi } from "./errands";
import type { ScheduleService } from "./schedule-service";
import type { RuleScanApi } from "./rule-scan";
import type { Canary } from "./canary";
import type { createActivation } from "./activation";
import type { createDocsNightly } from "./docs-nightly";
import type { createProbes } from "./probes";
import type { createReconcile } from "./reconcile";
import type { createStability } from "./stability";
import type { createStageChildren } from "./stages/children";
import type { createDocsStage } from "./stages/docs";
import type { createMemoryStage } from "./stages/memory";
import type { createNightStages } from "./stages/night";
import type { createOnboardingStage } from "./stages/onboarding";
import type { createProjectLifeStage } from "./stages/project-life";
import type { createQaStages } from "./stages/qa";
import type { createWriterHost } from "./writer-host";
import type { createWriterState } from "./writer/state";
import type { createWriterSpawn } from "./writer/spawn";
import type { createWriterVerify } from "./writer/verify";
import type { createWriterFinish } from "./writer/finish";
import type { createWriterStart } from "./writer/start";
import type { createWriterDispatch } from "./writer/dispatch";
import type { createWorkflowEngine } from "./workflow";
import type { createWorkflowTriggersService } from "./workflow-triggers-live";

type ActivationApi = ReturnType<typeof createActivation>;
type DocsNightlyApi = ReturnType<typeof createDocsNightly>;
type ProbesApi = ReturnType<typeof createProbes>;
type ReconcileApi = ReturnType<typeof createReconcile>;
type StageChildrenApi = ReturnType<typeof createStageChildren>;
type DocsStageApi = ReturnType<typeof createDocsStage>;
type MemoryStageApi = ReturnType<typeof createMemoryStage>;
type NightStagesApi = ReturnType<typeof createNightStages>;
type OnboardingStageApi = ReturnType<typeof createOnboardingStage>;
type ProjectLifeStageApi = ReturnType<typeof createProjectLifeStage>;
type QaStagesApi = ReturnType<typeof createQaStages>;
type WriterHostApi = ReturnType<typeof createWriterHost>;
type WriterStateApi = ReturnType<typeof createWriterState>;
type WriterSpawnApi = ReturnType<typeof createWriterSpawn>;
type WriterVerifyApi = ReturnType<typeof createWriterVerify>;
type WriterFinishApi = ReturnType<typeof createWriterFinish>;
type WriterStartApi = ReturnType<typeof createWriterStart>;
type WriterDispatchApi = ReturnType<typeof createWriterDispatch>;
type WorkflowEngineApi = ReturnType<typeof createWorkflowEngine>;
type WorkflowTriggersApi = ReturnType<typeof createWorkflowTriggersService>;

/** Every function one server module offers another; filled once all modules exist, read at call time. */
export interface Services {
  council: CouncilApi;
  canary: Canary;
  ruleScan: RuleScanApi;
  DOCS_NIGHT_ATTEMPTS: DocsNightlyApi["DOCS_NIGHT_ATTEMPTS"];
  DOCS_OPEN_KEY: DocsNightlyApi["DOCS_OPEN_KEY"];
  DOCS_TOOLING: DocsNightlyApi["DOCS_TOOLING"];
  DOCS_UNITS_OPEN_KEY: DocsNightlyApi["DOCS_UNITS_OPEN_KEY"];
  DOCS_UNIT_CONCURRENCY: DocsNightlyApi["DOCS_UNIT_CONCURRENCY"];
  WORKSPACE_DOCS_MIN_FILES: DocsNightlyApi["WORKSPACE_DOCS_MIN_FILES"];
  docsVerdict: DocsNightlyApi["docsVerdict"];
  docsPlaces: DocsNightlyApi["docsPlaces"];
  docsPlaceStatus: DocsNightlyApi["docsPlaceStatus"];
  docsLastRead: DocsNightlyApi["docsLastRead"];
  activate: ActivationApi["activate"];
  activeWriterTasks: WriterStateApi["activeWriterTasks"];
  providerBreaker: WriterStateApi["providerBreaker"];
  providerUsage: WriterStateApi["providerUsage"];
  providerRetry: WriterStateApi["providerRetry"];
  tasksMirror: WriterStateApi["tasksMirror"];
  concurrencyLimit: WriterStateApi["concurrencyLimit"];
  runBudgets: WriterStateApi["runBudgets"];
  runBudgetFor: WriterStateApi["runBudgetFor"];
  applyOnboardingPreview: OnboardingStageApi["applyOnboardingPreview"];
  assertComposerEnvironment: ActivationApi["assertComposerEnvironment"];
  dispatchCli: WriterDispatchApi["dispatchCli"];
  dispatchWriter: WriterDispatchApi["dispatchWriter"];
  docsPassesRunning: DocsNightlyApi["docsPassesRunning"];
  docsSpawnGate: DocsNightlyApi["docsSpawnGate"];
  docsUnitRecordKey: DocsNightlyApi["docsUnitRecordKey"];
  docsUnitsFinishing: DocsNightlyApi["docsUnitsFinishing"];
  docsUnitsIndexChain: DocsNightlyApi["docsUnitsIndexChain"];
  dropDocsUnitRecord: DocsNightlyApi["dropDocsUnitRecord"];
  enqueueResumedWriter: ReconcileApi["enqueueResumedWriter"];
  finishDocsUnit: DocsNightlyApi["finishDocsUnit"];
  finishWriterAttempt: WriterFinishApi["finishWriterAttempt"];
  ingestOpenCodeTelemetry: QaStagesApi["ingestOpenCodeTelemetry"];
  listedAgentProfiles: WriterHostApi["listedAgentProfiles"];
  maintainMemoryAfterAcceptance: MemoryStageApi["maintainMemoryAfterAcceptance"];
  maintainProjectLifeAfterAcceptance: ProjectLifeStageApi["maintainProjectLifeAfterAcceptance"];
  maybeFinishResumedAttempt: ReconcileApi["maybeFinishResumedAttempt"];
  persistWriterAcceptance: WriterVerifyApi["persistWriterAcceptance"];
  pluginStopped: DocsNightlyApi["pluginStopped"];
  projectLifeTaskSummary: StageChildrenApi["projectLifeTaskSummary"];
  readWriterWorkspaceFile: WriterDispatchApi["readWriterWorkspaceFile"];
  reconcileAttemptThread: ReconcileApi["reconcileAttemptThread"];
  reconcileDocsChild: StageChildrenApi["reconcileDocsChild"];
  reconcileProjectLifeChild: StageChildrenApi["reconcileProjectLifeChild"];
  reconcileStageChild: StageChildrenApi["reconcileStageChild"];
  recoverLostHolderThread: ReconcileApi["recoverLostHolderThread"];
  resolveProjectWriterHost: WriterHostApi["resolveProjectWriterHost"];
  resumeOrphans: ReconcileApi["resumeOrphans"];
  runBrowserQa: QaStagesApi["runBrowserQa"];
  resumeBrowserQaThreads: QaStagesApi["resumeBrowserQaThreads"];
  runDocsCatchUps: DocsNightlyApi["runDocsCatchUps"];
  runDocsMaintenance: DocsStageApi["runDocsMaintenance"];
  runDocsUnit: DocsNightlyApi["runDocsUnit"];
  runGateTriage: NightStagesApi["runGateTriage"];
  runMemoryContext: MemoryStageApi["runMemoryContext"];
  runMemoryMaintenance: MemoryStageApi["runMemoryMaintenance"];
  runNightFix: NightStagesApi["runNightFix"];
  runNightReview: NightStagesApi["runNightReview"];
  runNightlyDocs: DocsNightlyApi["runNightlyDocs"];
  runOnboardingPreview: OnboardingStageApi["runOnboardingPreview"];
  runProjectLifeMaintenance: ProjectLifeStageApi["runProjectLifeMaintenance"];
  runScheduledDocsMaintenance: DocsNightlyApi["runScheduledDocsMaintenance"];
  runVerification: WriterVerifyApi["runVerification"];
  runWorkspaceStatus: NightStagesApi["runWorkspaceStatus"];
  runWriterPool: WriterStateApi["runWriterPool"];
  saveDocsUnitRecord: DocsNightlyApi["saveDocsUnitRecord"];
  selectionCatalogHost: WriterHostApi["selectionCatalogHost"];
  spawnDocsThread: DocsNightlyApi["spawnDocsThread"];
  spawnWriterAttempt: WriterSpawnApi["spawnWriterAttempt"];
  isLiveFolder: WriterSpawnApi["isLiveFolder"];
  restoreLiveFolder: WriterSpawnApi["restoreLiveFolder"];
  startAmbiguousProbe: ProbesApi["startAmbiguousProbe"];
  startCancelProbe: ProbesApi["startCancelProbe"];
  startProviderErrorProbe: ProbesApi["startProviderErrorProbe"];
  startWriterTask: WriterStartApi["startWriterTask"];
  stability: ReturnType<typeof createStability>["stability"];
  threadReconcilePort: ReconcileApi["threadReconcilePort"];
  unitWritable: DocsNightlyApi["unitWritable"];
  updateDocsUnitsIndex: DocsNightlyApi["updateDocsUnitsIndex"];
  validateWriterResult: WriterVerifyApi["validateWriterResult"];
  waitWriter: WriterDispatchApi["waitWriter"];
  workspaceDirt: WriterSpawnApi["workspaceDirt"];
  workflowEngine: WorkflowEngineApi["workflowEngine"];
  workflowCatalog: WorkflowEngineApi["workflowCatalog"];
  workflowAgents: WorkflowEngineApi["workflowAgents"];
  workflowTriggers: WorkflowTriggersApi["workflowTriggers"];
  /** The errand starter of the PM tools (also used by scheduled errands); set when the tools are mounted. */
  errands: ErrandsApi;
  /** The schedule board: scheduler, definitions, previews (src/server/schedule-service.ts). */
  schedules: ScheduleService;
}
