import { experimental_defineHostEntry } from "@get-bb/plugin-sdk/host";
import { hostContract } from "./src/contracts";
import {
  connectOpencode,
  classifyPlan,
  coexistenceInventory,
  coexistenceOperation,
  gitOwnershipBase,
  gitOwnershipChanges,
  gitIntegrate,
  gitPrepareWorktree,
  gitCreateWorktree,
  gitRemoveWorktree,
  applyOnboardingPages,
  writeDocsPages,
  gitDocsScope,
  docsLineCounts,
  docsAnchors,
  docsVerifyCitations,
  docsFlows,
  docsDepth,
  docsStalenessHandler,
  gitCommitDocs,
  gitRevertPaths,
  listDocsPages,
  detect,
  importConfig,
  inspectCritiqueCoverage,
  install,
  readBoundedFile,
  readOpenCodeTelemetry,
  rollback,
  runCli,
  runCommand,
  runSandboxedCommand,
  runBrowserQa,
  probeBrowserQaTarget,
  snapshot,
  snapshotDryRun,
  writePmSettings,
  discoverClaudeAgentsHost,
  prepareNativeClaudeHost,
} from "./src/host-handlers";
import { sessionInventory } from "./src/session-inventory";
import { nativeInstallHost } from "./src/native-install-host";

export default experimental_defineHostEntry({
  contract: hostContract,
  handlers: {
    nativeInstall: nativeInstallHost,
    detect, coexistenceInventory, coexistenceOperation, gitOwnershipBase, gitOwnershipChanges, gitDocsScope, docsLineCounts, gitCommitDocs, gitRevertPaths, docsAnchors, docsFlows, docsDepth, docsVerifyCitations, docsStaleness: docsStalenessHandler, gitIntegrate, gitPrepareWorktree, gitCreateWorktree, gitRemoveWorktree, readOpenCodeTelemetry, readBoundedFile, listDocsPages, applyOnboardingPages, writeDocsPages, snapshotDryRun, snapshot, install, rollback, importConfig, connectOpencode, classifyPlan, inspectCritiqueCoverage,
    runCli, runCommand, runSandboxedCommand, runBrowserQa, probeBrowserQaTarget, writePmSettings, session_inventory: sessionInventory,
    discoverClaudeAgents: discoverClaudeAgentsHost, prepareNativeClaude: prepareNativeClaudeHost,
  },
});
